version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - DATABASE_URL=postgresql://pds:abc123@postgres:5432/pds_dev
      - DATABASE_TEST_URL=postgresql://pds:abc123@postgres:5432/pds_test
      - BROKER_URL=redis://:redispass@redis:6379/0
    expose:
      - 6000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    entrypoint: ./boot.sh

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - web

  postgres:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - db_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=pds
      - POSTGRES_PASSWORD=abc123
    expose:
      - 5432

  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - DATABASE_URL=postgresql://pds:abc123@postgres:5432/pds_dev
      - DATABASE_TEST_URL=postgresql://pds:abc123@postgres:5432/pds_test
      - BROKER_URL=redis://:redispass@redis:6379/0
    hostname: celery
    entrypoint: celery
    command: -A src.api.helpers worker --loglevel=info -Q celery --autoscale=10,1
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    entrypoint: celery
    command: flower --broker=redis://:redispass@redis:6379//

volumes:
  db_volume:
