version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - BROKER_URL=redis://:redispass@redis:6379/0
    expose:
      - 6000
    ports:
      - "6000:6000"
    volumes:
      - .:/app
    depends_on:
      - redis
    entrypoint: ./boot.sh

  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - BROKER_URL=redis://:redispass@redis:6379/0
    hostname: celery
    entrypoint: celery
    command: -A src.api.helpers worker --loglevel=info -Q celery --autoscale=10,1
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
